spring:
  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

server:
  error:
    include-message: always
